const workouts = [
  {day:'DAY 1',name:'PUSH',focus:'CHEST · SHOULDERS · TRICEPS',ex:[['Barbell Bench Press','Chest · Triceps'],['Incline Dumbbell Press','Chest · Shoulders'],['Overhead Shoulder Press','Shoulders · Triceps'],['Lateral Raises','Shoulders'],['Triceps Pushdown','Arms · Triceps']]},
  {day:'DAY 2',name:'PULL',focus:'BACK · REAR DELTS · BICEPS',ex:[['Lat Pulldown','Back · Arms'],['Seated Cable Row','Back · Arms'],['Chest Supported Row','Back'],['Face Pull','Shoulders · Back'],['Dumbbell Curl','Arms · Biceps']]},
  {day:'DAY 3',name:'LEGS',focus:'QUADS · HAMSTRINGS · GLUTES · CALVES',ex:[['Barbell Squat','Legs · Glutes'],['Romanian Deadlift','Legs · Glutes'],['Leg Press','Legs'],['Leg Curl','Legs'],['Standing Calf Raise','Legs · Calves']]},
  {day:'DAY 4',name:'PUSH',focus:'CHEST · SHOULDERS · TRICEPS',ex:[['Incline Barbell Press','Chest · Triceps'],['Machine Chest Press','Chest · Triceps'],['Cable Fly','Chest'],['Lateral Raises','Shoulders'],['Overhead Triceps Extension','Arms · Triceps']]},
  {day:'DAY 5',name:'PULL',focus:'BACK · REAR DELTS · BICEPS',ex:[['Pull Ups','Back · Arms'],['One Arm Dumbbell Row','Back'],['Reverse Fly','Shoulders · Back'],['Face Pull','Shoulders · Back'],['Hammer Curl','Arms · Biceps']]},
  {day:'DAY 6',name:'LEGS',focus:'QUADS · HAMSTRINGS · GLUTES · CALVES',ex:[['Hack Squat','Legs'],['Bulgarian Split Squat','Legs · Glutes'],['Hip Thrust','Glutes · Legs'],['Leg Extension','Legs'],['Seated Calf Raise','Legs · Calves']]},
];
const rules=['FORM > WEIGHT','FULL CONTROLLED REPS',"DON'T EGO LIFT",'PROGRESSIVE OVERLOAD','TRACK YOUR WORKOUTS','RECOVER PROPERLY','CONSISTENCY WINS'];
let active=0, query='', filter='ALL';
const saved=JSON.parse(localStorage.getItem('gymrat-data')||'{}');
const key=(day,i)=>`${day}-${i}`;
const esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function save(){localStorage.setItem('gymrat-data',JSON.stringify(saved))}
function demo(){return `<svg viewBox="0 0 160 170" aria-label="Animated exercise demonstration"><g class="person"><circle cx="80" cy="27" r="11"/><path d="M80 38v54M80 54l-31 24M80 54l31 24M80 92l-23 48M80 92l23 48"/></g><g class="moving weight"><path d="M33 69h94"/><path d="M40 60v18M120 60v18"/></g><path d="M12 152h136" stroke="#42503d"/></svg>`}
function form(ex){return `<div class="guide" id="guide-${ex.id}"><div class="demo">${demo()}</div><div class="guide-content"><div class="guide-box"><h4>STARTING POSITION</h4><p>Set your feet and brace your core. Keep joints stacked and a neutral spine before the first rep.</p></div><div class="guide-box"><h4>MOVEMENT</h4><p>Move through a controlled, pain-free range. Let the target muscle drive the rep—never momentum.</p></div><div class="guide-box"><h4>BREATHING & TEMPO</h4><p>Inhale and brace on the way down; exhale through the effort. 2 sec down → pause → 1 sec up.</p></div><div class="guide-box"><h4>KEY FORM CUES</h4><ul><li>Control every rep</li><li>Keep your core braced</li><li>Use full comfortable range</li></ul></div><div class="guide-box mistakes"><h4>COMMON MISTAKES</h4><ul><li>Ego lifting or rushing reps</li><li>Losing neutral spine</li><li>Using momentum or half reps</li></ul></div></div></div>`}
function tracker(ex){const sets=ex.sets||[{w:'',r:''},{w:'',r:''},{w:'',r:''},{w:'',r:''}];const last=ex.last?`Last time: ${ex.last}`:'Complete a logged workout to save a benchmark.';const suggestion=ex.last?'Suggestion: consider a small increase next session only if every rep stays clean.':'Form first—use a load you can fully control.';return `<div class="tracker"><div class="tracker-title"><span>WORKING SETS</span><span class="last">${last}</span></div><div class="sets">${sets.map((s,i)=>`<div class="set-row"><label>SET ${i+1}</label><input data-field="w" data-set="${i}" inputmode="decimal" placeholder="Weight kg" value="${esc(s.w)}"><input data-field="r" data-set="${i}" inputmode="numeric" placeholder="Reps" value="${esc(s.r)}"><button class="remove-set" data-remove="${i}" aria-label="Remove set">×</button></div>`).join('')}</div><button class="add-set">+ ADD SET</button><div class="last">${suggestion}</div></div>`}
function card(item,i){let ex=saved[key(active,i)]||{sets:[{w:'',r:''},{w:'',r:''},{w:'',r:''},{w:'',r:''}]}; ex={...ex,...{id:i,name:item[0],muscle:item[1]}};const complete=!!ex.complete;return `<article class="exercise ${complete?'complete':''}" data-id="${i}" data-name="${item[0].toLowerCase()}" data-muscle="${item[1].toLowerCase()}"><div class="card-main"><input class="check" type="checkbox" ${complete?'checked':''} aria-label="Mark ${item[0]} complete"><div><h3>${item[0]}</h3><span class="target">${item[1].toUpperCase()}</span></div><div class="prescription"><b>4 SETS × 6–10 REPS</b>90–120 SEC REST · INTERMEDIATE</div></div><button class="button guide-toggle">HOW TO PERFORM +</button>${form(ex)}${tracker(ex)}</article>`}
function render(){const w=workouts[active];dayNav.innerHTML=[...workouts.map((x,i)=>`<button class="${active===i?'active':''}" data-day="${i}">${x.day}<small> · ${x.name}</small></button>`),`<button class="${active===6?'active':''}" data-day="6">DAY 7 · REST</button>`].join('');if(active===6){workout.innerHTML=`<div class="workout-top"><div><p class="eyebrow">DAY 7</p><h2>REST / <em>RECOVERY</em></h2><p>Recovery is training. Walk, mobilize, eat well, and come back ready.</p></div><div class="progress"><div class="progress-label"><span>RESET COMPLETE</span><b>100%</b></div><div class="bar"><i style="width:100%"></i></div></div></div>`;return}const completed=w.ex.filter((_,i)=>saved[key(active,i)]?.complete).length;workout.innerHTML=`<div class="workout-top"><div><p class="eyebrow">${w.day} / PUSH · PULL · LEGS</p><h2>${w.name} <em>DAY.</em></h2><p>${w.focus}</p></div><div class="progress"><div class="progress-label"><span>WORKOUT PROGRESS</span><b>${completed} / 5 · ${completed*20}%</b></div><div class="bar"><i style="width:${completed*20}%"></i></div></div></div><div class="search-row"><input id="search" value="${query}" placeholder="Search exercises..." aria-label="Search exercises"><div class="filters">${['ALL','CHEST','BACK','SHOULDERS','ARMS','LEGS'].map(x=>`<button class="${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div></div><div class="cards">${w.ex.map(card).join('')}</div>`;applySearch()}
function applySearch(){document.querySelectorAll('.exercise').forEach(c=>{const hay=c.dataset.name+' '+c.dataset.muscle;c.hidden=!!(query&&!hay.includes(query.toLowerCase())||filter!=='ALL'&&!hay.includes(filter.toLowerCase()))})}
document.addEventListener('click',e=>{const day=e.target.closest('[data-day]');if(day){active=+day.dataset.day;query='';render();return}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const cardEl=e.target.closest('.exercise');if(!cardEl)return;const id=+cardEl.dataset.id, data=saved[key(active,id)]||{sets:[{w:'',r:''},{w:'',r:''},{w:'',r:''},{w:'',r:''}]};if(e.target.matches('.guide-toggle')){const guide=cardEl.querySelector('.guide');guide.classList.toggle('open');e.target.textContent=guide.classList.contains('open')?'CLOSE GUIDE −':'HOW TO PERFORM +'}if(e.target.matches('.add-set')){data.sets.push({w:'',r:''});saved[key(active,id)]=data;save();render()}if(e.target.matches('[data-remove]')){data.sets.splice(+e.target.dataset.remove,1);saved[key(active,id)]=data;save();render()}});
document.addEventListener('change',e=>{const cardEl=e.target.closest('.exercise');if(!cardEl)return;const id=+cardEl.dataset.id,data=saved[key(active,id)]||{sets:[{w:'',r:''},{w:'',r:''},{w:'',r:''},{w:'',r:''}]};if(e.target.matches('.check')){data.complete=e.target.checked;const first=data.sets.find(s=>s.w&&s.r);if(data.complete&&first)data.last=`${first.w} kg × ${first.r}`}if(e.target.matches('input[data-field]'))data.sets[+e.target.dataset.set][e.target.dataset.field]=e.target.value;saved[key(active,id)]=data;save();render()});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;applySearch()}});document.addEventListener('keydown',e=>{if(!/^[1-7]$/.test(e.key)||['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;active=+e.key-1;render();document.querySelector('#program').scrollIntoView({behavior:'smooth'})});
rulesList.innerHTML=rules.map((x,i)=>`<div class="rule"><b>0${i+1}</b><span>${x}</span></div>`).join('');
let remaining=90,initial=90,interval;const time=document.querySelector('#time'),timer=document.querySelector('.timer');function paint(){time.textContent=remaining?'': 'GO';if(remaining){time.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;timer.classList.remove('go')}else timer.classList.add('go')}document.querySelector('#presets').onclick=e=>{if(!e.target.dataset.time)return;remaining=initial=+e.target.dataset.time;clearInterval(interval);document.querySelectorAll('.presets button').forEach(b=>b.classList.toggle('selected',b===e.target));paint()};document.querySelector('#startTimer').onclick=()=>{clearInterval(interval);if(!remaining)remaining=initial;interval=setInterval(()=>{remaining--;paint();if(!remaining)clearInterval(interval)},1000)};document.querySelector('#pauseTimer').onclick=()=>clearInterval(interval);document.querySelector('#resetTimer').onclick=()=>{clearInterval(interval);remaining=initial;paint()};document.querySelector('#timerMin').onclick=()=>timer.classList.toggle('minimized');render();paint();
